### ISSUE TITLE
Tidak dapat Mengclone Pada Repositori Bersama

### ISSUE THREAD

**Issue by hakkansy** [Andi-IM/desktop-project#4]
![image](https://user-images.githubusercontent.com/62888652/110435888-26fed380-80e6-11eb-8398-f174535f9d40.png)

Selamat siang Andi. 
Untuk repositori milik saya sendiri sudah dapat saya lakukan clone. Akan tetapi, untuk melakukan clone terhadap repositori proyek bersama ini belum dapat saya lakukan clone. Mohon bantuannya ya.
Terimakasih.

**Comment by Andi-IM** [comment]
coba baca di tag #5 (Tidak bisa membuat clone) dan lakukan saran yang saya berikan.
