### ISSUE TITLE
Tidak bisa membuat clone

### ISSUE THREAD

**Issue by abidasshidiqienugraha** [Andi-IM/desktop-project#5]
![image](https://user-images.githubusercontent.com/66230558/110471914-4a8a4400-810f-11eb-9af6-394f34fa8d74.png)
### 

Selamat Malam Andi.
Ini Untuk Melakukan clonenya gak bisa. Mohon bantuannya ya.
Terimakasih.

**Comment by Andi-IM** [comment]
Jika sudah dipastekan, maka seharusnya tampilannya akan mejadi seperti ini :
![image](https://user-images.githubusercontent.com/21165698/110732284-795f0200-8256-11eb-9003-c10dcd5eb8ee.png)
Selamat Mencoba 👌🏼
